version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tray_fastapi_server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8030:8030"
    volumes:
      - ./FinderBack/app:/app/app
      - ./FinderBack/main.py:/app/main.py
      - ./FinderBack/.env:/app/.env
      - ./FinderInference/:/app/FinderInference
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: tray_mysql_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3300:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
